### ISSUE TITLE
Event matpref

### ISSUE THREAD

**Issue by jonatan-kruse** [careerfairsystems/nexpo-app#191]
Event, finns matpref på biljett? Ha en gräns gällande matpref för event, hur mycket mat och när beställs? -låsa anmälan

**Comment by jonatan-kruse** [comment]
@elnaseyer 
det finns ej på biljett men userId finns så går att hämta.
annars är förslag att be backend skicka med det i ticketDto:
från:
```ts
export interface TicketDto {
  userFirstName: string;
  userLastName: string;
  ticket: Ticket;
}
```
till:
```ts
export interface TicketDto {
  userFirstName: string;
  userLastName: string;
  userFoodPreferences: string | null;
  ticket: Ticket;
}
```
den svåra frågan är typ hur vi ska förmedla denna info till de som håller i eventet.

**Comment by elnaseyer** [comment]
Jo exakt, tänkte att man har det på ticket, så man inte kan ändra i efterhand! Utan isf att man måste ändra pref, sen boka av biljett och boka igen? 

Det andra är att tror inte det är mat på alla event, utan man hade kunnat märka event med mat. Göra så att om man bokar efter mat låsts får man notifikation eller liknande om att det antingen inte ingår man el inte kommer få matpref
