### ISSUE TITLE
Create details screen for company

### ISSUE THREAD

**Issue by emarforio** [careerfairsystems/nexpo-app#2]
When a company is clicked in the company list, a detailed view should open and show more information about the company. The information should be fetched from the backend.

Depends on #1

**Comment by berghdavid** [comment]
This issue is very similar: https://github.com/careerfairsystems/nexpo-app/issues/6
So the EventDetailsScreen could be used for inspiration if needed.

**Comment by Ikatji** [comment]
Figma sketch: https://www.figma.com/file/i6VN2PZNWNbZW3Ve8C1gqa/Company-Details?node-id=2%3A4
