### ISSUE TITLE
Create screen of events

### ISSUE THREAD

**Issue by berghdavid** [careerfairsystems/nexpo-app#4]
For starters we need to be able to view the different events happening during ARKAD. Therefore we need to create a list of clickable events. The events are retrieved from back-end and then put into the list.

- Retrieve events
- List them in a list
- Eventually lis them neatly in some sort of schedule

**Comment by emarforio** [comment]
Requires the functionality to be merged in the backend

**Comment by SirNaCl** [comment]
- [x] eventPreview component
- [x] eventList component
- [x] backend interaction

**Comment by berghdavid** [comment]
Similar implementation to CompaniesScreen has been added which uses newly made API-calls to the backend. A pretty UI/UX is needed though.
