### ISSUE TITLE
Handle responses from fetch method call (401, 404, ...)

### ISSUE THREAD

**Issue by berghdavid** [careerfairsystems/nexpo-app#42]
When using the Http-helpers calls we sometimes get bad responses from the server. It could be that the user isn't authorized (401) or that the address was not found (404). Either way it is nice to catch these errors and return a fitting object since they could be very bad depending on our implementation when using them. 

An example on how to solve this is shown here: 
https://stackoverflow.com/questions/59008723/javascript-how-to-handle-404-error-in-fetch

**Comment by emarforio** [comment]
The backend wraps the data in a "result object" (but it is not used for anything so the effort wasted) that could contain metadata such as request status and success. One solution could be to do something similar for the frontend. My suggestion is that we create a new type:

```typescript
export type HttpResult<T> = {
  success: boolean;
  message: string | null;
  data: T | null;
}
```

This type wraps a generic type T in an object that also contains metadata. The field `success` is a boolean that marks if the requst was successful. If it was, we can expect data to be in the `data` field if any is expected. If `success` is `false`, `data` should be empty (null) and message should instead be populated with a string that we can show to the user.

Two example objects in JSON-notation that satisfies `HttpResult<Company>` where `Company` just contains an id and name for brevity:

```json
{
  "success": true,
  "message": null,
  "data": {
    "id": 123,
    "name": "Example Company Inc"
  }
}
```
```json
{
  "success": false,
  "message": "You don't have permission to access this resource",
  "data": null
}
```

Then in the component that uses the API we can do something like this:

```typescript
// The function that gets and sets the company in the component, called on init and reload
const getCompany = async () => {
  setLoading(true);
  const companyResult = await API.companies.getCompany(companyId);
  setLoading(false);

  if (companyResult.success) {
    setCompany(companyResult.data);
  }
  else {
    setErrorMessage(companyResult.message);
  }
}
```

**Comment by jonatan-kruse** [comment]
Looks like a better way to handle theese errors are with try, catch and finally in the methods that make the api-calls.

Example:
```ts
const getEvents = async () => {
    try {
      setLoading(true);

      const events = await API.events.getAllEvents();
      setEvents(events);
      setUpcomingEvents(API.events.getUpcomingEvents(events));
      const bookedEvents = await API.events.getBookedEvents();
      setBookedEvents(bookedEvents);
    } catch (error) {
      
    } finally {
      setLoading(false);
    }
  }
```

**Comment by jonatan-kruse** [comment]
this is done incremently when we notice we need it...
