### ISSUE TITLE
As a Company I want to be able to connect with students (Scanning)

### ISSUE THREAD

**Issue by emarforio** [careerfairsystems/nexpo-app#57]
The company representatives should be able to scan a QR code on a Student's profile page and create a CompanyConnection (previously called Blip). This involves a QR-scanning screen that opens a modal on scan where the representative can rate the student and write a small comment and then save it.

Note that all scanning functionality is already implemented in a ready to use component: https://docs.expo.dev/versions/latest/sdk/bar-code-scanner/

**Comment by berghdavid** [comment]
- [x] Add a "scan  QR-code" button to host profile page.
- [x] Implement "BarCodeScanner"
- [x] Add a QR-code to the student profile page
- [x] Build the Modal popup
