### ISSUE TITLE
Create screen for an event

### ISSUE THREAD

**Issue by berghdavid** [careerfairsystems/nexpo-app#6]
To view more about an event there needs to be a screen which presents information about the event. The screen is reached by clicking on an event. The information about the event is retrieved from backend.

- Create a new screen for an event
- Retrieve data about the event from backend
- Organize and place the information neatly on the screen (name of event, place, time)

Depends on #4

**Comment by emarforio** [comment]
Requirements for done is just to present the information on a screen, styling and presentation is tracked in #25
