### ISSUE TITLE
Fix: EnterKeyHint prop on a DOM element

### ISSUE THREAD

**Issue by berghdavid** [careerfairsystems/nexpo-app#71]
When running expo in a web browser the following warning occurs which we would like to solve:

> Warning: React does not recognize the `enterKeyHint` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `enterkeyhint` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
>     in input (created by TextInput)
>     in TextInput (at TextInput.tsx:7)
>     in TextInput (at LoginScreen.tsx:54)
>     in div (created by View)
>     in View (at Themed.tsx:45)
>     in View (at LoginScreen.tsx:53)
>     in div (created by View)
>     in View (at Themed.tsx:45)
>     in View (at LoginScreen.tsx:48)
>     in LoginScreen (created by SceneView)
>     in StaticContainer
>     in StaticContainer (created by SceneView)
>     in EnsureSingleNavigator (created by SceneView)
>     in SceneView (created by CardContainer)
>     in div (created by View)
>     in View (created by CardContainer)
>     in div (created by View)
>     in View (created by CardContainer)
>     in div (created by View)
>     in View (created by ForwardRef(CardSheet))
>     in ForwardRef(CardSheet) (created by Card)
>     in div (created by View)
>     in View (created by AnimatedComponent)
>     in AnimatedComponent (created by ForwardRef(AnimatedComponentWrapper))
>     in ForwardRef(AnimatedComponentWrapper) (created by Card)
>     in Dummy (created by Card)
>     in div (created by View)
>     in View (created by AnimatedComponent)
>     in AnimatedComponent (created by ForwardRef(AnimatedComponentWrapper))
>     in ForwardRef(AnimatedComponentWrapper) (created by Card)
>     in div (created by View)
>     in View (created by Card)
>     in Card (created by CardContainer)
>     in CardContainer (created by CardStack)
>     in div (created by View)
>     in View (created by WebScreen)
>     in WebScreen (created by AnimatedComponent)
>     in AnimatedComponent (created by ForwardRef(AnimatedComponentWrapper))
>     in ForwardRef(AnimatedComponentWrapper) (created by MaybeScreen)
>     in MaybeScreen (created by CardStack)
>     in div (created by View)
>     in View (created by MaybeScreenContainer)
>     in MaybeScreenContainer (created by CardStack)
>     in CardStack (created by Context.Consumer)
>     in KeyboardManager (created by Context.Consumer)
>     in SafeAreaProviderCompat (created by StackView)
>     in div (created by View)
>     in View (created by StackView)
>     in StackView (created by StackNavigator)
>     in StackNavigator (at navigation/index.tsx:82)
>     in AuthNavigator (at navigation/index.tsx:51)
>     in EnsureSingleNavigator (created by ForwardRef(BaseNavigationContainer))
>     in ForwardRef(BaseNavigationContainer) (created by ForwardRef(NavigationContainer))
>     in ThemeProvider (created by ForwardRef(NavigationContainer))
>     in ForwardRef(NavigationContainer) (at navigation/index.tsx:46)
>     in Navigation (at App.tsx:18)
>     in div (created by View)
>     in View (created by NativeSafeAreaView)
>     in NativeSafeAreaView (created by SafeAreaProvider)
>     in SafeAreaProvider (at App.tsx:17)
>     in App (created by ExpoRootComponent)
>     in ExpoRootComponent
>     in div (created by View)
>     in View (created by AppContainer)
>     in div (created by View)
>     in View (created by AppContainer)
>     in AppContainer

**Comment by emarforio** [comment]
As far as I know, this is an Expo issue that has nothing to do with our app. It might be solved by upgrading the SDK version
