### ISSUE TITLE
Fix - Profile picture does not update

### ISSUE THREAD

**Issue by berghdavid** [careerfairsystems/nexpo-app#89]
When our fellow Business Manager tries to update their profile picture nothing happens. Not even after logging out is the profile picture updated. Below is their attempt to edit their profile picture.

- [ ] Users can now edit their profile picture

https://user-images.githubusercontent.com/47715964/141973509-b99e0f4f-12a5-4ab4-b8de-ddee251755c2.MP4

**Comment by emarforio** [comment]
Seems like file uploads and picking are not working properly on the app versions. They work on the web though. I have tried debugging on Android for a long time but there the picker does not even show. The permissions request does not show either and it only seems to be an issue on the standalone app which makes it a pain to debug
