### ISSUE TITLE
Create a screen for ticket details

### ISSUE THREAD

**Issue by emarforio** [careerfairsystems/nexpo-app#9]
This view should be able to show details about a ticket to an event.

Depends on #8

**Comment by berghdavid** [comment]
UI/UX Work can be continued in the ticket-details branch

**Comment by berghdavid** [comment]
The functionality is now implemented, what is left is building a pretty design.

**Comment by bubblyc** [comment]
UX: extend ticket on click and show the QR-code and option to change "photoOk"
